import React from "react";
import Document, { Html, Head, Main, NextScript } from "next/document";

class MyDocument extends Document {
	render() {
		return (
			<Html lang="pt-BR">
				<Head>
					<meta charSet="utf-8" />
					<meta name="theme-color" content="#000000" />
					<link rel="shortcut icon" href="/img/favicon.png" />
					<link
						rel="apple-touch-icon"
						sizes="76x76"
						href="/img/apple-icon.png"
					/>
					<meta name="description" content="Generated by create next app" />
					<link rel="preconnect" href="https://fonts.googleapis.com" />
					<link
						rel="preconnect"
						href="https://fonts.gstatic.com"
						crossOrigin={""}
					/>
					<link
						href="https://fonts.googleapis.com/css2?family=Inter:wght@200;400;600;800&display=swap"
						rel="stylesheet"
					/>
					<link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
				</Head>
				<body>
					<Main />
					<NextScript />
				</body>
			</Html>
		);
	}
}

MyDocument.getInitialProps = async (ctx) => {
	const originalRenderPage = ctx.renderPage;

	ctx.renderPage = () =>
		originalRenderPage({
			enhanceApp: (App) => (props) => <App {...props} />,
		});

	const initialProps = await Document.getInitialProps(ctx);

	return {
		...initialProps,
		styles: [
			<React.Fragment key="styles">{initialProps.styles}</React.Fragment>,
		],
	};
};

export default MyDocument;
